name: nginx
description: DNS and Ad-filtering for your network.
title: Nginx
type: application
version: 1.0.2
lib_version: 1.0.0
lib_version_hash: e40a5f95d4e70865b890baa66cd944e77077fa5db3ed5544f5498686ec2172ed
train: charts
app_version: v2
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
home: https://pi-hole.net/
icon: https://media.sys.truenas.net/apps/pihole/icons/icon.png
sources:
  - https://pi-hole.net/
  - https://github.com/truenas/charts/tree/master/charts/pihole
keywords:
  - networking
  - dns
run_as_context:
  - userName: root
    groupName: root
    gid: 0
    uid: 0
    description: Pi-hole runs as root user.
capabilities:
  - name: CHOWN
    description: Pi-hole is able to chown files.
  - name: FOWNER
    description: Pi-hole is able to bypass permission checks for it's sub-processes.
  - name: DAC_OVERRIDE
    description: Pi-hole is able to bypass permission checks.
  - name: SETGID
    description: Pi-hole is able to set group ID for it's sub-processes.
  - name: SETUID
    description: Pi-hole is able to set user ID for it's sub-processes.
  - name: SETFCAP
    description: Pi-hole is able to set file capabilities.
  - name: SETPCAP
    description: Pi-hole is able to set process capabilities.
  - name: NET_ADMIN
    description: Pi-hole is able to perform various network-related operations.
  - name: NET_BIND_SERVICE
    description: Pi-hole is able to bind to a privileged port.
  - name: NET_RAW
    description: Pi-hole is able to use raw sockets.
  - name: KILL
    description: Pi-hole is able to kill processes.
host_mounts: []
