name: mongodb
description: DNS and Ad-filtering for your network.
annotations:
  title: mongodb
type: application
version: 2.0.12
lib_version: 1.0.0
train: database
apiVersion: v2
appVersion: 2023.11.0
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
home: https://pi-hole.net/
icon: https://media.sys.truenas.net/apps/pihole/icons/icon.png
sources:
  - https://pi-hole.net/
  - https://github.com/truenas/charts/tree/master/charts/pihole
keywords:
  - networking
  - dns
