version: "3.5"

services:
  pihole:
    image: {{ ix_lib.charts.pihole.images.pihole_image_name("latest") }}
    container_name: {{ ix_lib.base.containers.container_name("pihole") }}
    environment:
      PIHOLE_INITDB_ROOT_USERNAME: {{ ix_lib.charts.pihole.utils.ADMIN_USERNAME }}
      PIHOLE_INITDB_ROOT_PASSWORD: {{ ix_lib.charts.pihole.utils.ADMIN_PASSWORD }}
    ports:
      - {{ ix_lib.charts.pihole.images.port_to_bind("21119") }}
    networks:
      - PIHOLE
    volumes:
      - type: volume
        source: PIHOLE_DATA
        target: /data/db

{% include 'library/templates/network.yaml' %}

networks:
  PIHOLE:
    name: {{ network }}

volumes:
  PIHOLE_DATA:
    name: {{ data_db_name }}
